process.env.NODE_ENV            = 'test';
process.env.JWT_ACCESS_SECRET   = 'test_access_secret_structbay_32_chars!!';
process.env.JWT_REFRESH_SECRET  = 'test_refresh_secret_structbay_32_chars!';
process.env.JWT_RESET_SECRET    = 'test_reset_secret_structbay_32_chars!!!';
process.env.JWT_ACCESS_EXPIRES_IN    = '15m';
process.env.JWT_REFRESH_EXPIRES_IN   = '30d';
process.env.JWT_REFRESH_EXPIRES_DAYS = '30';
process.env.JWT_RESET_EXPIRES_IN     = '1h';
process.env.FRONTEND_URL        = 'http://localhost:3000';
process.env.SMTP_HOST           = '';   // disabled — emails won't send in tests
